
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Refactor","number":19,"title":"Refactoring Code","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/19"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"ck-displaycoursestatus","number":17,"title":"Added course status to Course Search Results","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/17"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-PersonalSchedule-bug","number":16,"title":"Bug Fix for Creating Personal Schedule","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/16"}]
