
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"add-section-number-madhav-ucsb","number":34,"title":"Added section number column to search by course instructor. ","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"ck-finalexamjob","number":31,"title":"Implemented Admin Job to Update Final Exam Info","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/31"},{"author":{"id":"MDQ6VXNlcjg2OTg3NzQ0","is_bot":false,"login":"rdoumeth","name":""},"headRefName":"InstructorSearchBranch","number":20,"title":"Fix sections not showing up on instructor search","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-1/pull/20"}]
