name: "36-frontend-eslint: JavaScript style checking"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [ main ]
    paths: [frontend/**]


jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./frontend
      - run: npx eslint --max-warnings 0 .
        working-directory: ./frontend
